### ISSUE TITLE
Doesn't work?

### ISSUE THREAD

**Issue by alphapapa** [snosov1/toc-org#11]
I was excited to use this package, but it doesn't seem to be working.  I installed from MELPA and used the code in the instructions to add the hook.  Then I made a headline and gave it the `:TOC:` tag, but when I save the file, no table of contents is created.

Currently using Emacs 24.4 and Org 8.2.4.

When I eval the code to add the hook, this shows up in `*Messages*`:
```
(toc-org-enable org-mark-readonly (lambda nil (org-bullets-mode 1)) adp/org-mode-hook #[nil "ÅÆ	>
```
As you can see, there seems to be some garbage characters in there.  Either Emacs wouldn't copy it all to the clipboard, or Firefox wouldn't paste it all here.  :/

**Comment by snosov1** [comment]
Hey!

That's pretty awkward. I didn't make any changes for quite some time 

Let's try to make a "clean" experiment. 

1. Put 

```
(eval-after-load "toc-org-autoloads"
    '(progn
       (if (require 'toc-org nil t)
           (add-hook 'org-mode-hook 'toc-org-enable)
         (message "WARNING: toc-org not found"))))
```

into your `.emacs`

2. Restart Emacs
3. Open a file in org-mode, say `hello.org`. 
4. Make sure that the major mode is, in fact, org-mode. You can use `F1 m` for that
5. Make sure `org-mode-hook` contains `toc-org-enable` function. You can use `F1 v org-mode-hook` for that.
6. Type

```
* Hi
* Hello
* Good-bye
```

7. Save the file. Nothing should happen
8. Change the contents to 
```
* Hi
* Hello :TOC:
* Good-bye
```
9. Save the file. The contents should change to 
```
* Hi
* Hello :TOC:
 - [[#hi][Hi]]
 - [[#good-bye][Good-bye]]

* Good-bye
```

Please, let me know if it works.

**Comment by alphapapa** [comment]
Hi,

Thanks for the quick response!

I ran your tests exactly as you described, and it did indeed work fine!  So then I opened the file I tried to add a TOC to before...and it doesn't work.  When I save the file, the `:TOC:` heading doesn't change at all.

I'm guessing that there must be something in the file itself that is causing the problem...and, yes, I just found it.  When I remove this heading from the file, it works:
```org
* Screenshot
Here's an example of what you get in Emacs from capturing [[http://kitchingroup.cheme.cmu.edu/blog/2014/07/17/Pandoc-does-org-mode-now/][this page]]:
[[screenshot.png]]
```
...and then, after reverting the buffer, and leaving that headline in the file...it still works.  This is very weird.

The file in question is the readme here: https://github.com/alphapapa/org-protocol-capture-html  Maybe you can figure out what's going on.  :)

Thanks, it sure is nice when it works!  :D

**Comment by snosov1** [comment]
Thanks! I'll have a look!

**Comment by snosov1** [comment]
Just had a look. Couldn't reproduce the issue with the provided file.

Please, let me know if this (or some other) issue is still bothering you.

**Comment by alphapapa** [comment]
Thanks.  Yeah, I'm not sure what the problem was.  If it happens again I'll let you know.  Keep up the good work.  :)
