### ISSUE TITLE
add better  toc-org-special-chars-regexp

### ISSUE THREAD

**Issue by JAremko** [snosov1/toc-org#12]
Current  [toc-org-special-chars-regexp](https://github.com/snosov1/toc-org/blob/master/toc-org.el#L64) misses some characters.  Can we use the same one that GitHub [uses](https://github.com/jch/html-pipeline/blob/40124bfc1e2085f12cbde64caea3af37343a0629/lib/html/pipeline/toc_filter.rb#L26)  ?  Here is a test string `"Set AA053 Лыв № mon_osced font size(设置等宽字体）"`    
） - isn't what you think :smile:  
`replace-regexp-in-string` with  `"\\W"` outputs  `"#setaa053Лывавдыmonospacedfontsize设置等宽字体"` It  should be `"set-aa053-Лыв--mon_osced-font-size设置等宽字体"`so we probably need something like  this `"[^\\w\\-_ ]"` but for some reason it removes  everything.

**Comment by snosov1** [comment]
fixed by https://github.com/snosov1/toc-org/pull/13
