### ISSUE TITLE
[Github] Handle duplicate headings correctly

### ISSUE THREAD

**Issue by dvcrn** [snosov1/toc-org#16]
As explained in https://github.com/snosov1/toc-org/issues/1#issuecomment-211863739

If a heading is appearing more than once on github pages, github is appending a number to the anchor (`messagelist-1). 

Here's a generated example with the current functionality:

```
   - [[#general][General]]
     - [[#authentication][Authentication]]
   - [[#requests][Requests]]
     - [[#messagelist][message:list]]
   - [[#events][Events]]
     - [[#messagelist][message:list]]
```

Here's how it should look like:

```
   - [[#general][General]]
     - [[#authentication][Authentication]]
   - [[#requests][Requests]]
     - [[#messagelist][message:list]]
   - [[#events][Events]]
     - [[#messagelist-1][message:list]]
```

**Comment by alphapapa** [comment]
Does toc-org need to have a GitHub-specific mode?  Because wouldn't fixing this cause non-GitHub-rendered links to break?

**Comment by dvcrn** [comment]
@alphapapa toc-org does have a github specific mode: https://github.com/snosov1/toc-org#use

**Comment by alphapapa** [comment]
Haha, oops, I forgot.  :)
