### ISSUE TITLE
Heading priorities cause broken links

### ISSUE THREAD

**Issue by alphapapa** [snosov1/toc-org#18]
I just noticed that headings that have priorities generate invalid links, e.g.: https://github.com/alphapapa/helm-org-rifle/blob/20b890a814acb6889a2adb2b5b7d236396374a5e/notes.org The two links under the `Bugs` heading are invalid both in GitHub's rendering and in Emacs buffers.

**Comment by snosov1** [comment]
Thanks!

Some activity on the issue tracker, while I was away! =)

Anyway, now I'm finally back home and it looks like I have some work to do on the weekend =)

A reproducing example:

```
* TOC :TOC:
 - [[#bugs][Bugs]]
   - [[#c-negation-only-error][[#C] Negation-only error]]
   - [[#b-helm-org-rifle-tags-matching][[#B] helm-org-rifle tags matching]]

* Bugs
** [#C] Negation-only error
** [#B] helm-org-rifle tags matching
```

**Comment by alphapapa** [comment]
Ah, sorry, I should have provided the minimum sample myself.  :)  Thanks.

**Comment by snosov1** [comment]
That's ok. You did the hardest part finding the bug ;)
