### ISSUE TITLE
Releases for MELPA stable

### ISSUE THREAD

**Issue by juliangehring** [snosov1/toc-org#19]
Since the package looks very mature, it would be great to also have it available on MELPA stable (http://stable.melpa.org). The only step that would be needed for this is to create releases on github that follow the MELPA convention (https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md):

> To have a stable version generated for your package simply tag the repository using a naming compatible with version-to-list. The repo state of this tag will be used to generate the stable package.

This would also allow users who want to rely on stable version of emacs packages to also use your great package.

**Comment by snosov1** [comment]
Hey and thank you! 

I'm traveling right now and I only have my phone with me. I'll be back in a week or so and will have a look then. Thanks!

**Comment by snosov1** [comment]
Hey!

I believe that should do it: https://github.com/snosov1/toc-org/releases/tag/1.0.0

Please, ping me if something's still missing

**Comment by juliangehring** [comment]
Thank you, it look great: http://stable.melpa.org/#/toc-org

**Comment by snosov1** [comment]
:+1:
