### ISSUE TITLE
carry over TODOs, tags, progress cookies

### ISSUE THREAD

**Issue by VladimirAlexiev** [snosov1/toc-org#25]
It would be really nice if it can carry over extra headline info into the generated TOC, like the HTML exporter does. Eg see http://vladimiralexiev.github.io/Multisensor/validation.html:

![image](https://cloud.githubusercontent.com/assets/536250/16516595/7bfb7eca-3f81-11e6-9494-a16592fcecbc.png)

**Comment by snosov1** [comment]
I'm not sure I understand this.

You mean the link text should contain stuff like TODO states? I.e.

`* TODO Hello` should convert to `- [[#hello][TODO Hello]]`? If yes, I'm not sure it's feasible for this package.

**Comment by VladimirAlexiev** [comment]
@csantosb suggests in https://github.com/csantosb/helm-perso-wiki/wiki/Extra to use `:TOC:noexport:` which allows the HTML export to generate its own TOC (with `toc:t`). So I'm happy to close this.

**Comment by snosov1** [comment]
:+1:
