### ISSUE TITLE
toc-org-enable to add TOC headline if missing

### ISSUE THREAD

**Issue by VladimirAlexiev** [snosov1/toc-org#26]
Something for `toc-org-enable`:
```elisp
    (setq  ; toc-org puts TOC in the org file, so these conflict
       org-export-with-section-numbers nil
       org-export-with-toc nil)
    ;; add TOC headline if missing
    (unless (org-find-exact-headline-in-buffer "Table of Contents")
      (org-first-headline-recenter)
      (beginning-of-line)
      (insert "* Table of Contents                                 :TOC_5:\n\n"))
```

Why `:TOC_5:` not `:TOC_2:` ? See #27

**Comment by snosov1** [comment]
Not sure I understand the problem.

**Comment by csantosb** [comment]
I think the idea is to auto instert a TOC in none exists.

Personally, I would prefer you let the user customize this package behavior, for
example with

    (advice-add 'toc-org-insert-toc :before #'toc-org-advice)

You define your own `toc-org-advice`, as the one above

**Comment by snosov1** [comment]
> I think the idea is to auto insert a TOC in none exists.

You mean right after opening the file? Or what? I still don't fully understand =)

**Comment by csantosb** [comment]
Well, when `toc-org-insert-toc` acts, that's to say, `before-save-hook`. No need to modify the package to achieve this, in my opinion.

**Comment by snosov1** [comment]
Yeah, if you want to generate the TOC right after you open the file, you can use `find-file-hook`. Not sure it's a good idea, though. Some time ago, this was a default behavior of the mode, but I eliminated that.

**Comment by csantosb** [comment]
Up to the user to decide ... ! I am using [this](https://github.com/csantosb/helm-perso-wiki/wiki/Extra) setup, which fits me.

**Comment by VladimirAlexiev** [comment]
If this mode depends on a `:TOC:` heading, I think it should ensure (or at least have an option to do it).
But I'm also happy to close this. @csantosb thanks, your code is better, esp `:noexport:` so I can use the "native" `toc:t` for html export

**Comment by snosov1** [comment]
Ok, let's close it. Thx!
