### ISSUE TITLE
use custom variables for options

### ISSUE THREAD

**Issue by VladimirAlexiev** [snosov1/toc-org#27]
Expressing one's preferences in the TOC tag (eg as the default `:TOC_2_gh:`) is not quite proper style. 
Eg in #26 I prefer `:TOC_5:` while the default is `:TOC_2:`.

It's better to use purely `:TOC:` to mark the headline, but have custom variables for these options.
- for the depth, use eg `org-toc-level`. You could use the value of `org-export-with-toc`, if number, to set this (that's the variable used by HTML export)
- for the style, use eg `org-toc-style`

**Comment by snosov1** [comment]
Actually, you can use either way already. There are variables `toc-org-max-depth` and `toc-org-hrefify-default`. You can set them in your config, if you prefer.

**Comment by VladimirAlexiev** [comment]
sorry for not checking first!

**Comment by snosov1** [comment]
No problem!

**Comment by Knusper** [comment]
> Actually, you can use either way already. There are variables `toc-org-max-depth` and `toc-org-hrefify-default`. You can set them in your config, if you prefer.

It would be cool if this variable is mentioned in the documentation.  I used it a long time ago, and now I use the package again, and the absence of this variable in the documentation confused me a bit, because I knew this was possible.

**Comment by snosov1** [comment]
Here you go!

https://github.com/snosov1/toc-org/commit/d992b1f76addea2f97c4996a279b1b4202c82bb9
