### ISSUE TITLE
Links don't work if headline has any TODO or statistics-cookie

### ISSUE THREAD

**Issue by VladimirAlexiev** [snosov1/toc-org#28]
Look at https://github.com/VladimirAlexiev/VladimirAlexiev.github.io/blob/master/Multisensor/validation.org.
Only the first two links work, because the other headlines have a TODO or statistics-cookie, but Github doesn't strip these when generating the preview. Eg
- for `Validation [1/16]`, github generates `#validation116` but my patch #24 links to `#validation-` (forgot a trailing space that is converted to `-`).
- for `TODO Underscores to Spaces`, github generates `#todo-underscores-to-spaces` but you link to `#underscores-to-spaces`

This means that:
- you should strip TODO and statistics-cookies from link label, but leave them in link href (stripping punctuation and converting to lowercase) 
- the links won't work in org-mode (but I think that's ok since there's enough navigation facilities there)
- the links won't be stable (fixing a task to DONE will change its anchor, and the cookies of all its ancestors). We should give up the idea of stable links in github, unless they fix their code

**Comment by snosov1** [comment]
> for TODO Underscores to Spaces, github generates #todo-underscores-to-spaces but you link to #underscores-to-spaces

Not exactly. By default, GitHub strips TODO keywords. But it seems to leave it if you have `#+OPTIONS: todo:t` in your file. I think that's fixable.

**Comment by snosov1** [comment]
I've pushed statistics cookies handling to https://github.com/snosov1/toc-org/tree/handle-statistics-cookies

Please, check this if you have a chance.

Next, I'll try to figure something out about TODO handling.

**Comment by VladimirAlexiev** [comment]
Here's a quick patch re TODO:
```elisp
      ;; strip states
      (unless org-export-with-todo-keywords
        (goto-char (point-min))
        (while (re-search-forward toc-org-states-regexp nil t)
          (replace-match "" nil nil nil 1)))
```

toc-org-states-regexp hard-codes a few, but as you know I can customize them in the file. Eg my file [validation.org](https://github.com/VladimirAlexiev/VladimirAlexiev.github.io/blob/master/Multisensor/validation.org) has
```
#+TODO: TODO QUE | DONE CANCEL
```
And so if I evaluate the following variables I get
```
org-todo-keywords ;; ("TODO" "QUE")
org-done-keywords ;; ("DONE" "CANCEL")
```
All these are put in `org-todo-line-regexp`, which is used in `(org-get-todo-state)`. The keyword is in match group 2.

NOW, whether you use the hard-coded toc-org-states-regexp or org functions to process this, depends on whether GitHub processes the `#+TODO` heading.

Cheers!

**Comment by snosov1** [comment]
I've re-implemented the fixes in https://github.com/snosov1/toc-org/tree/fix-28, since I didn't like the original implementation. Both issues seem to be fixed there, so, please, give it a try.

A couple of comments:

> Here's a quick patch re TODO:

Thx! However, you can't use `org-export-with-todo-keywords` variable in this package, since GitHub doesn't know about it. I've implemented something similar.\

> toc-org-states-regexp hard-codes a few, but as you know I can customize them in the file.

GitHub was handling only TODO and DONE states the last time I checked. So, no plans to support anything else either.

**Comment by snosov1** [comment]
I've also added a couple of tests. Personally, I'm ready to merge it - please, have a look, and if you're ok with it, let's merge & close this:

https://github.com/snosov1/toc-org/tree/fix-28

**Comment by VladimirAlexiev** [comment]
looks ok
