### ISSUE TITLE
Tests are breaking? 

### ISSUE THREAD

**Issue by agzam** [snosov1/toc-org#34]
I'm on Spacemacs Emacs 25.1 OSX GUI. Whenever I try to run tests with ert, it also adding toc-org related tests to the runner (have no idea why), and `test-toc-org-insert-toc` seems to be failing. I'm not sure how those tests get added to the "UNIVERSE" (whatever that means). And not sure why one of them failing

**Comment by snosov1** [comment]
Hey!

I've moved the tests into a separate file. It should solve the problem with `toc-org` tests loading unintentionally. However, on the actual failing side, I can't really reproduce it (as I described in the original ticket). 

Can you provide clear steps for reproduction, by any chance?

**Comment by agzam** [comment]
@snosov1 Yeah I think it is fixed now. Thanks!
