### ISSUE TITLE
Don't export toc in LaTeX format

### ISSUE THREAD

**Issue by thblt** [snosov1/toc-org#52]
Sorry if I'm missing something obvious, but I can't find a way to prevent the toc from being exported to LaTeX.  Is there a way?

Thanks!

**Comment by snosov1** [comment]
Hey!

You can add `:noexport:` tag to the toc heading (it's a standard way to prevent exporting). Does it work for you?

**Comment by thblt** [comment]
My mistake: I misunderstood my own problem :)  I wanted a ToC in Github but I had assumed Github's renderer respected `:noexport:`, which it actually doesn't.  So everything's fine indeed, `:noexport:`ing the ToC leaves it visible in Github.  Thanks!

**Comment by sangjeedondrub** [comment]
Disable exporting the ``toc'' generated by `toc-org' package.

```lisp
(setq org-export-exclude-tags (quote ("noexport" "NOEXPORT" "hide" "HIDE" "TOC" "toc")))
```

Enable exporting `org-mode''s ``toc'' to LaTeX or HTML.

```
#+options: toc:t
```
