### ISSUE TITLE
The table of contents section is numbered.

### ISSUE THREAD

**Issue by mgoldenbe** [snosov1/toc-org#53]
I use `#+OPTIONS: num:t` to have my sections numbered in `GitHub`. How do I prevent the `Table of contents` section (i.e. the one tagged `:TOC:`) from being numbered? In particular, I tried to use `#+PROPERTY: UNNUMBERED:t`, but this line gets removed when I save the file.

**Comment by snosov1** [comment]
Hey, @mgoldenbe !

You're right - the `UNNUMBERED` property is the "org" way to do this. However, as far as I can tell, GitHub implementation doesn't support this property - at least I couldn't find any signs of it in the source. This, pretty much, means that I can't do anything about it on my end and you have to look for the implementation on the [org-ruby](https://github.com/wallyqs/org-ruby) side first.
