### ISSUE TITLE
Subtree-specific TOC

### ISSUE THREAD

**Issue by joonro** [snosov1/toc-org#55]
Hi - 

Thank you very much for the great package. 

Since I often to export subtrees instead of an entire file, it would be great if it becomes possible to create the automatic toc at the subtree level. For example, with the following:

```org
* Heading
** Table of Contents    :TOC:
** Subheading1
** Subheading2
```

desired output is:

```org
* Heading
** Table of Contents    :TOC:
- Subheading1
- Subheading2
** Subheading1
** Subheading2
```

**Comment by snosov1** [comment]
Hey!

On the surface, it seems like it's not too hard to implement, but it would kinda be a breaking change. Can you, please, provide more details about your use case, so, maybe, I could better understand the value of this?

**Comment by snosov1** [comment]
Hey, @joonro !

Sorry, I wasn't on to it for quite some time. After thinking about it a bit - I'm hesitant to add this feature. Historically, `toc-org` operates under the assumption that there's going to be only one TOC. Complicating this logic will, probably, add ambiguity that will require some mechanism to resolve it. All in all, I don't think it's worth it.

In your particular case, I believe, that you'll be better off having a separate file for each of your lectures - it'll be cleaner from many perspectives, I think. And `toc-org` will handle it naturally =)

**Comment by alphapapa** [comment]
@joonro https://github.com/alphapapa/org-make-toc supports multiple ToC's in a single file.  Here are some [examples](https://github.com/alphapapa/org-make-toc/blob/master/example.org).

**Comment by joonro** [comment]
@snosov1 Thanks a lot for your reply. @alphapapa Thanks a lot for the pointer. I will definitely check it out!
