### ISSUE TITLE
"upcase-fix" question

### ISSUE THREAD

**Issue by JAremko** [snosov1/toc-org#58]
toc-org has [an interesting line](https://github.com/snosov1/toc-org/blob/cd1868787c64dbeec010e2a07dc465105e60a5fc/toc-org.el#L197) 
```elisp
(upcase-fix (replace-regexp-in-string "[A-Z]" 'downcase spc-fix t))
````
It makes me like this: :thinking: 

Why doing `(downcase "s[s]-_SS")`  that will output `s[s]-_ss` isn't sufficient?

**Comment by snosov1** [comment]
Actually, I don't think it has any special purpose. All other "fixers" use `replace-regexp-in-string` so, I guess, I just used it mechanically without thinking too much about it. 

Thanks for the note, I've replaced it with a simpler call. (I guess, it might also help non-English languages, if github can handle them).
