### ISSUE TITLE
Why not an interactive command such as "toc-org-mode"?

### ISSUE THREAD

**Issue by mrbig033** [snosov1/toc-org#60]
I rarely use this command, and I wish to enable it selectively. No need to put it in `org-mode-hook`. Just add it to `after-save-hook` when enabled.

**Comment by snosov1** [comment]
Hey, @mrbig033 !

`toc-org` should really be a minor mode and I have no idea why I haven't implemented it this way from the start. Please, take a look at #61 and tell me if it does it for you. (BTW, with the current version you can call `toc-org-insert-toc` interactively)

**Comment by snosov1** [comment]
Ok, I've merged it. Please, let me know if you face any issues.

**Comment by mrbig033** [comment]
It's working perfectly, thanks!
