### ISSUE TITLE
Doesn't strip TODO keywords.

### ISSUE THREAD

**Issue by tktujy** [snosov1/toc-org#65]
I set up single-letter keys for TODO keywords. These look like

```
#+TODO: TODO(t) | DONE(d!)
```

Then I found these keywords are not stripped.

**Comment by snosov1** [comment]
I don't believe I recognize this syntax. Is it, actually, a valid org line (and does GitHub recognize it?)? I'd believe, the syntax should be  `#+TODO: t | d` (in which case it works)

**Comment by tktujy** [comment]
I got this syntax from [Org Mode Manual](http://www.gnu.org/software/emacs/manual/html_node/org/Fast-access-to-TODO-states.html), and Github can recognize it.

**Comment by snosov1** [comment]
I also looked through the docs, but somehow it got me confused. Sorry.

Anyway, should be handled correctly, [now](https://github.com/snosov1/toc-org/commit/5ce7c249207b617c72febb27dbad7076342c1afd).
