### ISSUE TITLE
is there anyway to specify link href for headline?

### ISSUE THREAD

**Issue by PoiScript** [snosov1/toc-org#67]
I noticed that `toc-org` will always create a href from the headline name even after providing a `CUSTOM_ID` property:

```org
* toc :TOC:
- [[#headline][headline]]

* headline
:PROPERTIES:
:CUSTOM_ID: id
:END:
``` 

I'm wondering is there anyway to specify it?

**Comment by snosov1** [comment]
Hey, @PoiScript !

Unfortunately, no. The thing is - GitHub doesn't handle properties and sticks to his own way of hrefifying headings. So, I see very little value in supporting it. Frankly, I see little value in it even if it wasn't for GitHub =)
