### ISSUE TITLE
Cookies tracking progress in a headline breakes links in the TOC

### ISSUE THREAD

**Issue by thermopyle** [snosov1/toc-org#70]
If I have a headline like this;

```
** Task headline [2/2]
*** DONE Subtask headline
*** DONE Another subtask headline
```
the resulting link in the TOC will look like this;
`- [[#task-headline-22][Task headline]]`

The link will be unusable. Removing the [2/2] and saving makes the link usable.

**Comment by snosov1** [comment]
Hey, @thermopyle !

What exactly do you mean by "link will be unusable"? For one thing, GitHub doesn't strip the cookies for link generation, so it works on github alright (see https://github.com/snosov1/org-toc ).

**Comment by thermopyle** [comment]
Navigating in Emacs from the TOC item using `C-c C-o` doesn't work.

**Comment by snosov1** [comment]
Gotcha! [That ](https://github.com/snosov1/toc-org/pull/71) should do it. Please, try on your end.

**Comment by thermopyle** [comment]
Will do as soon as I can. Let you know the result.

**Comment by thermopyle** [comment]
It works! Thanks!
