### ISSUE TITLE
depth control tag doesn't work

### ISSUE THREAD

**Issue by spacerainbow000** [snosov1/toc-org#79]
I tried tagging a header like `:TOC_8:` and still got a TOC of depth 2; I had to change the setting `toc-org-max-depth` in custom to change the depth. I'm also not seeing where in the code this tag is meant to be processed

**Comment by snosov1** [comment]
[This](https://github.com/snosov1/toc-org/blob/df4ad6ff15e3b02f6322305638a441a636b9b37e/toc-org.el#L61) is the regexp that accounts for _ and @ separators.

[This](https://github.com/snosov1/toc-org/blob/df4ad6ff15e3b02f6322305638a441a636b9b37e/toc-org.el#L394) is where the depth is being assigned to either the value specified in the tag or the value from `toc-org-max-depth`.

I've also wanted to add a url to a test for that specific functionality, but realized that I have only tests for format of the tag (not testing "depth functionally" really).

Do you still see the problem? If yes, do you care to provide a test that fails ? (and a fix, if possible =) )
