### ISSUE TITLE
Internal linking (C-c C-o) doesn't work in Org 8.3

### ISSUE THREAD

**Issue by snosov1** [snosov1/toc-org#8]

**Comment by louy2** [comment]
Seems to me the order of invoking has changed, so the custom ID compliant link only triggers custom ID translation. I don't see it mentioned in the changelog though. [Org 8.3 changelog](http://orgmode.org/Changes.html)

**Comment by snosov1** [comment]
I've started a thread on org mailing list, since it seems like `org-translate-link` function and the related functionality was overlooked, when they changed the way links are represented in code.

https://lists.gnu.org/archive/html/emacs-orgmode/2015-08/msg00833.html

**Comment by snosov1** [comment]
Ok, the issue seem to be fixed in Org upstream.

Commit [93b73bd3032bf03f129c81fb199fbaeb31a772a3](http://orgmode.org/w/org-mode.git?p=org-mode.git;a=commit;h=93b73bd3032bf03f129c81fb199fbaeb31a772a3) fixes the `org-translate-link` function. So, a version of Org that contains this commit is needed in order for linking to work. (Personally, I don't when it will be available through ELPA. The last available ELPA version to the moment - `org-20150817` -  doesn't have it.)

**Comment by louy2** [comment]
Maybe they can have a develop branch on MELPA.

**Comment by snosov1** [comment]
Don't know about that. 

Anyway, my guess is that they should put bugfix releases once in a while on their own package archive. But I don't know for sure and how long it might take.

**Comment by snosov1** [comment]
It turns out that Org packages are put to ELPA almost on a weekly basis. So, now, the available version 20150824 contains the fix and seems to work fine.

**Comment by louy2** [comment]
:+1: Thank you!
