### ISSUE TITLE
If the org file has no headers, everything is deleted

### ISSUE THREAD

**Issue by dmgerman** [snosov1/toc-org#81]
I wrote a document with no headers (I forgot to add them), then added

* Table of contents :toc:

at the top.

The moment I saved the file, everything was deleted.

It might be useful to have some type of marker to delimite where the old header ends, so it does not delete text beyond that.

**Comment by snosov1** [comment]
Hey, @dmgerman !

Well, Org does have a marker for that. Namely, a star character `*` to start a new header. I'm not sure Org has anything else and in that case, I'm not sure `toc-org` needs to invent/introduce a way to do this. Please, let me know if you have some specific ideas

**Comment by dmgerman** [comment]
One idea I have: if the file has no header (*, except for the :toc: one), then do nothing.
