### ISSUE TITLE
Export the document to html

### ISSUE THREAD

**Issue by Cletip** [snosov1/toc-org#88]
Hi!
Your package works perfectly for me, but I can't export to html. 
I found two solutions: 
- the first one, put "(setq org-export-with-broken-links nil)"
- the second one, put :TOC: AND :noexport: on the heading which has the table of contents

I write these lines to tell you this problem, even if for me it is not really annoying ^^

**Comment by snosov1** [comment]
Hey, @Cletip !

Thanks for reaching out! In fact, your second solution is the intended one (i.e. it is a feature, not a bug).

If you feel like a change to the documentation would help you to save some time and/or frustration, I suggest that you submit a PR.

**Comment by Cletip** [comment]
Yes this is a feature, but I can't export my table of contents created with toc-org, right ?
Maybe it is not the purpose ^^

**Comment by snosov1** [comment]
Yeah, for things like exporting to html you should ask the exporting backend to generate the toc (it's built in functionality). toc-org does not try to reimplement that

**Comment by Cletip** [comment]
Ok I understand perfectly, so my request is useless.
Thanks for the clarification!
