### ISSUE TITLE
markdown example should include !

### ISSUE THREAD

**Issue by masukomi** [snosov1/toc-org#89]
in the readme it suggests you need to add `<-- :TOC: -->` to your header. The problem with this is that you end up with a big `<-- :TOC -->` displayed in your header. The plugin works if you make it an html comment `<!-- :TOC: -->` which is hidden (as desired) when you render the markdown.

ask: update the readme to include the `!` so that people know they can do that instead.

**Comment by snosov1** [comment]
[Done](https://github.com/snosov1/toc-org/commit/6d3ae0fc47ce79b1ea06cabe21a3c596395409cd)

Not sure what I was thinking when I wrote this =)
